# Generated by Django 4.2.16 on 2025-03-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolstaff',
            unique_together={('user', 'school')},
        ),
        migrations.AddIndex(
            model_name='schoolstaff',
            index=models.Index(fields=['school', 'role'], name='accounts_sc_school__04fbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolstaff',
            index=models.Index(fields=['user'], name='accounts_sc_user_id_4db8aa_idx'),
        ),
    ]
