# Generated by Django 4.2.16 on 2024-11-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_schoolstaff_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualification',
            field=models.JSONField(),
        ),
    ]
