# Generated by Django 4.2.16 on 2024-11-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_teacherprofile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacheravailability',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='preferred_subjects',
            field=models.JSONField(default=list, help_text='List of preferred subjects for this time slot'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('TENTATIVE', 'Tentative')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='teacheravailability',
            index=models.Index(fields=['teacher', 'date', 'status'], name='accounts_te_teacher_64c82d_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacheravailability',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='check_end_time_after_start_time'),
        ),
    ]
