# Generated by Django 4.2.16 on 2025-02-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='matching_algorithm_settings',
            field=models.JSONField(default=dict, help_text='Custom settings for teacher matching algorithm'),
        ),
    ]
