# Generated by Django 4.2.16 on 2025-02-20 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstituteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MATHS', 'Mathematics'), ('SCIENCE', 'Science'), ('ENGLISH', 'English'), ('SOCIAL', 'Social Studies'), ('COMPUTER', 'Computer Science'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('BIOLOGY', 'Biology'), ('HISTORY', 'History'), ('GEOGRAPHY', 'Geography'), ('CIVICS', 'Civics'), ('ECONOMICS', 'Economics'), ('BUSINESS', 'Business Studies'), ('ACCOUNTANCY', 'Accountancy'), ('COMMERCE', 'Commerce'), ('PSYCHOLOGY', 'Psychology'), ('PHILOSOPHY', 'Philosophy'), ('POLITICAL_SCIENCE', 'Political Science'), ('HINDI', 'Hindi'), ('SANSKRIT', 'Sanskrit'), ('FRENCH', 'French'), ('GERMAN', 'German'), ('SPANISH', 'Spanish'), ('JAPANESE', 'Japanese'), ('CHINESE', 'Chinese'), ('ITALIAN', 'Italian'), ('KOREAN', 'Korean'), ('OTHER', 'Other')], max_length=20)),
                ('grade', models.CharField(choices=[('NURSERY', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th'), ('9', '9th'), ('10', '10th'), ('11', '11th'), ('12', '12th'), ('OTHER', 'Other')], max_length=20)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('Other', 'Other')], default='A', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_ACCEPTANCE', 'Awaiting Acceptance'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('HYBRID', 'Hybrid')], default='ONLINE', max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(default=dict, help_text='Specific requirements for the substitute teacher')),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_substitutions', to=settings.AUTH_USER_MODEL)),
                ('original_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_classes', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_substitutions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_requests', to='accounts.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('substitute_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitutes.substituterequest')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('INVITATION', 'Invitation'), ('ASSIGNMENT', 'Assignment')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='substituterequest',
            index=models.Index(fields=['school', 'date', 'status'], name='substitutes_school__e124b3_idx'),
        ),
        migrations.AddIndex(
            model_name='substituterequest',
            index=models.Index(fields=['assigned_teacher', 'date'], name='substitutes_assigne_b76f68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requestinvitation',
            unique_together={('substitute_request', 'teacher')},
        ),
    ]
