# Generated by Django 4.2.16 on 2025-02-21 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('substitutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinvitation',
            name='batch_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requestinvitation',
            name='response_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requestinvitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='requestinvitation',
            name='substitute_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='substitutes.substituterequest'),
        ),
        migrations.AlterField(
            model_name='requestinvitation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
