# Generated by Django 4.2.16 on 2024-12-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substituterequest',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('Other', 'Other')], default='A', max_length=20),
        ),
    ]
