# Generated by Django 4.2.16 on 2024-12-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes', '0002_substituterequest_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substituterequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_ACCEPTANCE', 'Awaiting Acceptance'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
