# Generated by Django 4.2.16 on 2025-04-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes', '0002_requestinvitation_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substituterequest',
            name='host_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substituterequest',
            name='requirements',
            field=models.JSONField(blank=True, default=dict, help_text='Specific requirements for the substitute teacher'),
        ),
    ]
