# Generated by Django 4.2.16 on 2024-12-01 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('substitutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('students', models.ManyToManyField(blank=True, related_name='attended_sessions', to=settings.AUTH_USER_MODEL)),
                ('substitute_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='substitutes.substituterequest')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
