# Generated by Django 4.2.16 on 2025-04-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecording',
            name='history_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='jiomeet_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='room_pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='recording_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionrecording',
            name='size',
            field=models.BigIntegerField(blank=True, help_text='Size in bytes', null=True),
        ),
    ]
